<?php

$g_arrLevels = [1 =>
	[
		'molecule' => "Rudieum",
		'formula' => "OC<sub>2</sub>H",
		'map' => [
			'xxxxxxxx',
			'x      x',
			'x      x',
			'x xxxx x',
			'x x  x x',
			'x x  x x',
			'x xx x x',
			'x      x',
			'xxxxxxxx',
		],
		'atoms' => [
			[3,4,"H"],
			[4,4,"O"],
			[3,5,"C"],
			[4,5,"C"],
		],
		'target' => [
			'CH',
			'OC',
		],
	],

	[
		'molecule' => 'Water',
		'formula' => 'H<sub>2</sub>O',
		'map' => [
			'xxxxx',
			'x   x',
			'x   xxxxxx',
			'x  x     x',
			'x x      xx',
			'x x    xx x',
			'x    x x  x',
			'xxx x  x  x',
			' x        x',
			' xxxxxxxxxx',
		],
		'atoms' => [
			[3, 2, 'H'],
			[3, 7, 'H'],
			[8, 6, 'O'],
		],
		'target' => [
			'HOH',
		],
	],

	[
		'molecule' => 'Methane',
		'formula' => 'CH<sub>4</sub>',
		'map' => [
			'xxxxxxxxxxxxx',
			'x   x  x    x',
			'x x  x x    x',
			'x  x   x  x x',
			'x      xxxx x',
			'x       x x x',
			'x    x  x   x',
			'x xxxxx    xx',
			'x   x  x   x',
			'xxxxx  x   x',
			'       xxxxx',
		],
		'atoms' => [
			[6, 2, 'H'],
			[2, 6, 'H'],
			[2, 8, 'H'],
			[9, 5, 'H'],
			[8, 3, 'C'],
		],
		'target' => [
			' H ',
			'HCH',
			' H ',
		],
	],

	[
		'molecule' => 'Methanol',
		'formula' => 'CH<sub>3</sub>OH',
		'map' => [
			'         xxxx',
			'xxxx     x  x',
			'x  x     x  x',
			'x  xx   xx  x',
			'x   xxxxx   x',
			'x x x  x    x',
			'x      x    x',
			'x  x x   x  x',
			'x           x',
			'x   x x   x x',
			'xxxxxx    x x',
			'     xxxxxxxx',
		],
		'atoms' => [
			[3, 4, 'H'],
			[1, 8, 'H'],
			[6, 10, 'H'],
			[9, 6, 'H'],
			[6, 5, 'C'],
			[11, 3, 'O'],
		],
		'target' => [
			' H ',
			'HCOH',
			' H ',
		],
	],

	[
		'molecule' => 'Ethylene',
		'formula' => 'C<sub>2</sub>H<sub>4</sub>',
		'map' => [
			'xxx     xxx',
			'x x     x x',
			'x xxxxxxx x',
			'x      x  x',
			'xx    x   x',
			'x x     x x',
			'x   x    xx',
			'x  x      x',
			'x xxxxxxx x',
			'x x     x x',
			'xxx     xxx',
		],
		'atoms' => [
			[1, 2, 'H'],
			[4, 4, 'C'],
			[7, 5, 'H'],
			[9, 5, 'C'],
			[8, 7, 'H'],
			[9, 7, 'H'],
		],
		'target' => [
			'H  H',
			' CC',
			'H  H',
		],
	],

	[
		'molecule' => 'Propylene',
		'formula' => 'C<sub>3</sub>H<sub>6</sub>',
		'map' => [
			' xxxxxxxxx  ',
			' x x x x x  ',
			' x x x x xxx',
			'xx   x x x x',
			'x      x x x',
			'x x      x x',
			'x x x      x',
			'x x x x   xx',
			'xxx x x x x ',
			'  x x x x x ',
			'  xxxxxxxxx ',
		],
		'atoms' => [
			[2, 1, 'H'],
			[2, 3, 'H'],
			[1, 4, 'H'],
			[3, 4, 'H'],
			[4, 3, 'C'],
			[6, 3, 'H'],
			[8, 4, 'C'],
			[3, 6, 'C'],
			[5, 8, 'H'],
		],
		'target' => [
			' HH H',
			'HCCC',
			' HH H',
		],
	],

	[
		'molecule' => 'Ethanal',
		'formula' => 'CH<sub>3</sub>CHO',
		'map' => [
			'xxxxxxxxxxx',
			'x         x',
			'x xx   xx x',
			'x         x',
			'x xxx xxx x',
			'x         x',
			'x xxx xxx x',
			'x         x',
			'x xx   xx x',
			'x         x',
			'xxxxxxxxxxx',
		],
		'atoms' => [
			[1, 3, 'H'],
			[1, 5, 'H'],
			[1, 6, 'C'],
			[3, 9, 'O'],
			[5, 5, 'H'],
			[5, 6, 'H'],
			[7, 3, 'C'],
		],
		'target' => [
			' HH',
			'HCCO',
			' H',
		],
	],

	[
		'molecule' => 'Ethanol',
		'formula' => 'C<sub>2</sub>H<sub>6</sub>O',
		'map' => [
			'     xxxxx  ',
			'     x   x  ',
			' xxxxx x x  ',
			' x       x  ',
			' xxx    xx  ',
			'   x x x xxx',
			'   xx    x x',
			'xxxx       x',
			'x      x   x',
			'xxxxx x  x x',
			'   x    x  x',
			'   xxxxxxxxx',
		],
		'atoms' => [
			[6, 1, 'H'],
			[7, 1, 'C'],
			[8, 3, 'H'],
			[4, 4, 'H'],
			[6, 5, 'H'],
			[5, 6, 'H'],
			[5, 7, 'C'],
			[2, 8, 'O'],
			[10, 10, 'H'],
		],
		'target' => [
			' HH',
			'HCCOH',
			' HH',
		],
	],
];
