<?php

$g_arrLevels = [1 =>
	[
		'map' => [
			'xxx xx',
			'o    x',
			'x    x',
			'x    x',
			'x    o',
			'xoxxx ',
		],
		'stones' => 3,
	],

	[
		'map' => [
			'         xx',
			'        xxx',
			'     xxx x ',
			'   ox     x',
			'  o       x',
			' o        x',
			'o     xx  x',
			'x      x  x',
			'x         x',
			'x         x',
			'x         o',
			' oox     x ',
			'  ox    x  ',
			'   xxxxx   ',
		],
		'stones' => 8,
	],

	[
		'map' => [
			'        xx    ',
			'       x  x   ',
			'  xx   x   x  ',
			' x  o  x    x ',
			'o    x x    x ',
			'x     x    x  ',
			' x        x   ',
			'  oo       xx ',
			'    o        o',
			'   x         o',
			'  x    xx   x ',
			'  x    x xxx  ',
			'   x   x x    ',
			'    xxx  x    ',
			'         x    ',
			'         xx   ',
		],
		'stones' => 7,
	],

	[
		'map' => [
			'    xxxo    ',
			'   x    o   ',
			'  x      o  ',
			' x      x o ',
			' x     x  x ',
			'x      x   x',
			'x       x  x',
			'x     xx x x',
			'x    x    xx',
			'x    x     x',
			' x        x ',
			'  x      x  ',
			'   x    x   ',
			'    xxxx    ',
		],
		'stones' => 4,
	],

	[
		'map' => [
			'           oooo ',
			'        ooo   o ',
			'   x  oo     o  ',
			'   x x      o   ',
			'   x x      o   ',
			'   x x     x  xx',
			'xx x xx    xxxx ',
			' xxxxxxxx  x    ',
			'  xxxxxxxxx     ',
			'  xx            ',
			'  x             ',
		],
		'stones' => 13,
	],

	[
		'map' => [
			'          xxo ',
			' ox      x  o ',
			'x  xxxxxx   o ',
			'x          x  ',
			' o         x  ',
			'  x        x  ',
			'  o   o     o ',
			' o           x',
			' x           x',
			' x          xx',
			'  oxx       xx',
			'     xxxxxxxx ',
		],
		'stones' => 10,
	],

	[
		'map' => [
			'             x  ',
			'            x x ',
			'           x   x',
			'  xxxxxxxxx  xx ',
			' x          x   ',
			'x x         x   ',
			'x  x  xxxxx x   ',
			'x  xxx    xxx   ',
			'  oo  o  oo  o  ',
			'  o    o o    o ',
			' o      o      x',
		],
		'stones' => 12,
	],

	[
		'map' => [
			'     xxxxx    ',
			'   xx     ox  ',
			'  o         o ',
			' x          x ',
			'x          x x',
			'x        x   x',
			'x       xx   x',
			'x            x',
			'x   x        x',
			'x       x   x ',
			' x         x  ',
			'  o      oo   ',
			'   oxxxxx     ',
		],
		'stones' => 7,
	],

	[
		'map' => [
			'      xx       ',
			'  xx  x x  oo  ',
			'   xoxx  xx o  ',
			'    o      o   ',
			'xxxx  xxx x    ',
			' xx  xx x  xxx ',
			'   x  xxx     x',
			'   o        xx ',
			'  x oxx xx  x  ',
			'  x o x x x x  ',
			'   x  x x x x  ',
			'      x x  xx  ',
			'       x       ',
		],
		'stones' => 8,
	],

	[
		'map' => [
			'      x       ',
			'oxxxxxxxxxxox ',
			'              ',
			'       xxxxoxx',
			'              ',
			'              ',
			'              ',
			'        xx o  ',
			' xxxxxxxxxx x ',
			'         oo x ',
			'o       x   x ',
			' xxxxxxx    x ',
			'  xxxxxxxxxo  ',
		],
		'stones' => 8,
	],

	[
		'map' => [
			'           o    ',
			'          o     ',
			'         o      ',
			'  o     o     o ',
			' x   x x   x o  ',
			' x  x x  x x x o',
			' x x x  x x x x ',
			' x x x x x  x x ',
			'x  x xx x  x xx ',
			'x x x x x  x x  ',
			'x x x x x  x x  '
		],
		'stones' => 8,
	],

	[
		'map' => [
			'     xxxx      ',
			'   xx    x     ',
			'  xxx    xxx   ',
			' xxxxx  x   xxx',
			'xxxx    x      ',
			'   xx  x   xxxx',
			'    xxx   x    ',
			'    xx   x     ',
			'     o   o     ',
			'     o    o    ',
			'     oo    o   ',
			'      oo    xxx',
			'       oo      ',
			'        oo     ',
			'          o    ',
		],
		'stones' => 14,
	],

	[
		'map' => [
			'  xxx    ooo   ',
			'   x x  x x    ',
			'    xx  xo  xx ',
			'xxx        xxx ',
			'xxx         x  ',
			'  xx           ',
			'    o    o  xx ',
			'            xx ',
			'            xx ',
			'            xx ',
			'           ox  ',
			'       x   ox  ',
			'      ox   oxxx',
			'            x  ',
			'            x  ',
		],
		'stones' => 10,
	],
];
