<?php

return [
	['101',				'BLACKJACK',									'The Blackjack where 21 pays double pay and the dealer stops at 17 and goes at 16'],
	['101b',			'CARD COUNTING',								'Learn yourself to count cards'],
	['101c',			'BLACKJACK',									'You know Jack... Rules inside!'],
	['102',				'MINESWEEPER',									'Default field of 9*9 containing 10 mines! The faster you play, the better your score'],
	['102c_analyze',	'Minesweeper analyzer',							'A minesweeper test in JS'],
	['102d_create',		'Create Minesweeper maps',						'A minesweeper test in JS'],
	['104',				'BLACKBOX - PHP',								'Find the Atoms by sending beams into the field'],
	['141',				'BLACKBOX - JS',								'Find the Atoms by sending beams into the field'],
	['187',				'BLACKBOX - GRIDGAME',							'Find the Atoms by sending beams into the field'],
	['105',				'CARRACE',										'Race a bitmap car with your cursor. You need a steady hand and a good mouse for this'],
	// ['106',				'JAVACAVE',										"You're a lonely snake trying to make his way home... Dont bump the walls, use your spacebar"],
	// ['107',				'TRAPPED',										"You're a dot and your trapped. Typical, right? Get outta there"],
	// ['108',				'DEFEND YOUR CASTLE',							'For the real die-harders! This game keeps you up at night. It does get bored after a few hours and you might get handinjuries'],
	// ['109',				'GRIDLOCK (Flash)',								'Get the coloured fcker out of the grid. Do so by moving all others'],
	['188',				'GRIDLOCK (JS)',								'From Flash'],
	['110',				'CUMULARI ABSOLUTUS',							'A mathematical problem. I want the sum of the absolute values of all 25 fields to be 1... Impossible?'],
	// ['111',				'STICK',										'Make as much money as possible within a set or unset amount of days. Whats your tcatics?'],
	['115',				'MASTERMIND',									'Its old, but its stil good! Its a braincracker'],
	['116',				'CIJFERS',										'Thats me playing. Try it out, might be fun'],
	['117',				'QUIZ',											'For the brainiacs among us. A few questions you can bust your head on'],
	// ['119',				'PICROSS',										'Tricky puzzle. You can make it as big as you want though'],
	// ['119B',			'PICROSS - Editor',								'Level editor for PICROSS'],
	['120',				'WORDMIX',										'Just a few mixed words and a sentence. Get it right and you wiiiiiin'],
	['121',				'POKER',										'Play poker on your own'],
	['123',				'Stepping stones',								'Eliminate all stones but one, to reach the ultimate score: 1'],
	['123B',			'Stepping stones - Editor',						'Create your own Steppin stones level'],
	['124',				'SAFE CRACKING',								'Crack the safe by choosing the four right numbers'],
	['125',				'HOW FAST ARE YOU?',							'Very simple JS game. Hit the field as soon as possible when it turns red!'],
	['127',				'NUMBER GUESSING',								'Try to guess the number in as few tries as possible'],
	['128',				'HOW COMPUTER CREATED EARTH',					'The story about God, Earth, the creation and those )#$)(@!#& computers'],
	['131',				"PHP POKER TEXAS HOLD'EM TEST",					'A test to benchmark my PHP PokerTexasHoldem class'],
	['131b',			"TEXAS HOLD'EM TEST",							'A test to benchmark my new PokerTexasHoldem class'],
	// ['132',				'MULTIPLAYER POKER',							"Play Poker Texas Hold'em with 3 other people"],
	// ['133',				'DOPEWARS',										'Deal drugs to make lots and lots of moneeehy'],
	// ['134',				'TIC TAC TOE',									'The classic'],
	['134b',			'TIC TAC TOE v2',								'Gridgame version of TTT'],
	// ['136',				'SUDOKU -DoItYourself',							'Make your own sudoku or try one of the earlier'],
	// ['137',				'KIDS SUDOKU',									'Make your own very easy sudoku and play it'],
	['139',				'THE BOX - One Target',							'Get all boxes in that one corner'],
	['140',				'THE BOX - More Targets',						'Every box has one place to go to. Not as easy as One Target'],
	['140B',			'THE BOX - Editor',								'Create your own The Box level'],
	// ['142',			"MP TEXAS HOLD'EM v2",							"Play Poker Texas Hold'em with up to 9 other people"],
	['143',				'ABALONE',										'Speel Play Abalone online'],
	['145',				'LINX',											'Connect the dots, kinda'],
	['145B',			'LINX - Editor',								'Create your own LINX level'],
	['146',				'SLITHER',										'Connect the slither'],
	['146b',			'SLITHER 2',									'Connect the slither. Mobile optimized'],
	['146c',			'SLITHER 3',									'Gridgame version of Canvas Slither'],
	['147',				'QUICK CLICKER',								'!!NEW!!'],
	['148',				"EINSTEIN'S RIDDLE",							'Are you in the top 2% smartest people in the world? Can you solve the puzzle?'],
	['149',				'SHIFTER',										'Think first, shift later'],
	['150',				'SWITCHBOARD',									'Connect the relais to make all lights light up'],
	['151',				'TOWERS OF HANOI',								'8 disks, 3 towers, make the moves'],
	// ['152',			'Fibonacci',									''],
	['153',				'F1 Racer',										'Click-race a circuit'],
	['153B',			'F1 Racer - Editor',							'Create your own F1 Racer level'],
	['154',				'Maze',											''],
	['156',				'Tetravex',										'The Ubuntu ripoff'],
	['157',				"Fortune's Tower - JS",							"It's a Fable II Pub game"],
	['158',				"Fortune's Tower - PHP",						"It's a Fable II Pub game"],
	['159',				'Atomix',										'Create molecules from atoms'],
	['159B',			'Atomix - Editor',								'Create your own Atomix level'],
	['160',				'Pixelus',										'Get the pixels to their targets'],
	['160B',			'Pixelus - Editor',								'Create your own Pixelus level'],
	['161',				'Bioshock hacker',								'From the game: hack a machine'],
	['162',				'Marbles',										'My very own marbles2.com ripoff'],
	['163',				'Entangled',									'Entangled ripoff: less HTML5, more CSS3 and JS'],
	['164',				'Machinarium I',								'Stole a fun game from Machinarium'],
	['164B',			'Machinarium I - Editor',						'Create your own Machinarium I level'],
	['165',				'Machinarium II',								'Stole another fun game from Machinarium'],
	['165B',			'Machinarium II - Editor',						'Create your own Machinarium II level'],
	['167',				'Filling',										'Trying to make separate areas by size...'],
	['168',				'Flood',										'Flood the board by propagating a color. You start at the top left'],
	['169',				'Rectangles',									''],
	['170',				'Mahjong',										'Mahjong Solitaire in CANVAS'],
	['170B',			'Mahjong - Editor',								'Build a Mahjong Solitaire map!'],
	['171',				'Traffic',										'Very simple traffic simulation'],
	['172',				'Word',											'Reorder the letters to make a word'],
	['173',				'Mamono sweeper',								'HTML version of the Flash game'],
	['174',				'Mondrian puzzle',								'Mondrian square puzzle'],
	['175',				"Knight's Minesweeper",							'Minesweeper with different detecting neighbors'],
	['176',				'Memory',										'You know memory. Play against yourself'],
	['177',				'Squarescape',									'As seen on and stolen from the Play store'],
	['177B',			'Squarescape - Editor',							'Create your own Squarescape level'],
	['178',				'Laser',										'As seen on and stolen from the Play store'],
	['178B',			'Laser - Editor',								'Create your own Laser level'],
	['179',				'Pythagorea',									'As seen on and stolen from the Play store'],
	['181',				'ZHOR',											'As seen on and stolen from the Play store'],
	['181B',			'ZHOR - Editor',								'Create your own ZHOR level'],
	['183',				'Fallout Hacking Helper',						'Cheat with Fallout hacking'],
	['184',				'BLOCK 3x Solver',								'Because BLOCK 3x is too hard...'],
	['185',				'Tetris Solver',								'Because Tetris grids are boring, but necessary'],
	['186',				'0h h1',										'From Android'],
	['189',				'0h n0',										'From Android'],
	['190',				'Bridges',										'From Android'],
	['191',				'Keer Op Keer SOLO',							'Speel Play Solo Keer Op Keer online'],
	['192',				'Hitomezashi',									'Hitomezashi Stitch Pattern'],
//	['193',				'INDEX grid concept',							'A prototype games index'],
	['194',				'Keer Op Keer MULTI',							'Speel Play Keer Op Keer samen multiplayer'],
	['195',				"TEXAS HOLD'EM v3",								"Multi-player Poker Texas Hold'em"],
	['196',				'Labyrinth / Betoverde Doolhof SOLO',				"Speel De Betoverde Doolhof. Play Labyrinth"],
	['197',				'Picross 2',									"Picross, but better"],
	['199',				'Track Switcher / De Spoorwerf',				"Move trains on a train yard"],
	['200',				'Project L SOLO',								"Tetris puzzler for points, against the computer"],
	['201',				'Labyrinth / Betoverde Doolhof MULTI',			"Play Labyrinth Speel Betoverde Doolhof online"],
];
